services:
  mediporta:
    image: mediporta
    build:
      context: .
      dockerfile: Mediporta/Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - mediporta-database
        
        
  mediporta-database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mediporta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432